version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=tenebrosa.c5gcys4o2llz.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Tenebrosa2026!

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:3001
    ports:
      - "8080:80"
    depends_on:
      - backend
